name: Maven Package Deployment

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Matches the <id> in distributionManagement of pom.xml
        settings-path: ${{ github.workspace }} # Path where settings.xml will be written

    # Write settings.xml file for GitHub Packages
    - name: Configure Maven settings.xml
      run: |
        echo "<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>" > $GITHUB_WORKSPACE/settings.xml

    # Clean cached data
    - name: Clear Maven Cache
      run: mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false
  
    # Build the project with Maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    # Deploy to GitHub Packages
    - name: Deploy to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
